# Generated by Django 3.2 on 2021-05-01 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.TextField(default='')),
                ('plot', models.TextField(default='')),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(upload_to='')),
                ('genre', models.CharField(choices=[('액션', '액션'), ('스릴러', '스릴러'), ('로맨스', '로맨스'), ('코미디', '코미디'), ('뮤지컬', '뮤지컬'), ('판타지', '판타지'), ('애니메이션', '애니메이션')], default='액션', max_length=10)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
