# Generated by Django 3.2 on 2021-05-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0002_alter_content_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='poster',
            field=models.ImageField(upload_to='posters'),
        ),
    ]
