# Generated by Django 3.2 on 2021-05-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0003_alter_content_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='poster',
        ),
    ]
