# Generated by Django 3.2 on 2021-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0005_alter_content_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
    ]
