# Generated by Django 3.2 on 2021-05-01 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0006_content_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
